### ISSUE TITLE
Cursor invisible after exiting with Ctrl+C

### ISSUE THREAD

**Issue by NyCodeGHG** [DRSchlaubi/mcserv#12]
![Peek 2021-09-04 14-39](https://user-images.githubusercontent.com/37078297/132094733-538f7a94-6a73-4943-ad1b-f41cc1a243bd.gif)

**Comment by DRSchlaubi** [comment]
This sounds like a bug of interact

**Comment by NyCodeGHG** [comment]
that's what I thought

**Comment by DRSchlaubi** [comment]
See https://github.com/frencojobs/interact/issues/3

**Comment by frencojobs** [comment]
Hi. Interact v2.1 should have a [reset](https://github.com/frencojobs/interact#handling-exceptions) function you can use with a try-catch block. It doesn't directly help with Ctrl+C exits, but you can catch a Ctrl+C so it should be good.

**Comment by DRSchlaubi** [comment]
`ProcessSignal.sigint.watch().listen()`, doesn't call the listener. Any ideas?

**Comment by DRSchlaubi** [comment]
Need to wait for @frencojobs on this one (https://github.com/frencojobs/interact/issues/3#issuecomment-913034525)
