### ISSUE TITLE
Installing newer 1.19.x Paper versions fails with error

### ISSUE THREAD

**Issue by CrazyJannis44** [DRSchlaubi/mcserv#47]
Windows: 11
mcserv: newest version according to winget

![screenshot](https://user-images.githubusercontent.com/36644360/192074125-1ea71a6d-ff16-457d-aa24-bdec7ad10167.png)

**Comment by DRSchlaubi** [comment]
Fixed in: https://github.com/DRSchlaubi/mcserv/releases/tag/v0.2.1
