### ISSUE TITLE
Source file cab1.cab 

### ISSUE THREAD

**Issue by Schokommuffin** [DRSchlaubi/mcserv#7]
Im on Windows and the .msi dont stops telling me:
Source file not found
C:\Users\...\Downloads\cab1.cab  Verify
that the file exists and you can access it.

**Comment by DRSchlaubi** [comment]
Looks like I missed this
https://stackoverflow.com/a/11285208

**Comment by NyCodeGHG** [comment]
Fixed in 62cb9ee
