### ISSUE TITLE
Application Directory Detection is broken under linux

### ISSUE THREAD

**Issue by NyCodeGHG** [DRSchlaubi/mcserv#9]
Tested on 0.0.1.
![image](https://i.imgur.com/rUzvOv0.png)

**Comment by DRSchlaubi** [comment]
This works like intended.
The version.txt is expected to be in the same folder as the binary

**Comment by NyCodeGHG** [comment]
It doesn't work as intended. There is a version.txt in the folder, but the path is missing its leading slash
